name: GJS
on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: vx.x.x
      - name: Install npm dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test:deno
