name: GJS
on:
  pull_request:
  push:

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install GJS
        run: sudo apt-get --yes install gjs
      - name: Install npm dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test:gjs
  # mac:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 16
  #     # See https://github.com/GiovanniBussi/macports-ci-action/blob/master/.github/workflows/main.yml
  #     - name: Setup MacPorts
  #       uses: GiovanniBussi/macports-ci-action@master
  #     - name: Install GJS
  #       run: sudo port install gjs
  #     - name: Install npm dependencies
  #       run: npm install
  #     - name: Build
  #       run: npm run build
  #     - name: Test
  #       run: npm run test:gjs
